# Generated by Django 3.0 on 2020-06-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forum_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Forum'),
        ),
    ]
