# Generated by Django 3.0.7 on 2020-06-20 21:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('sub_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('dept_code', models.CharField(choices=[('TM', '12101'), ('PY', '12102'), ('LG', '12104'), ('ME', '12105'), ('IC', '12110'), ('FT', '12112'), ('DM', '12113'), ('EN', '12115'), ('EE', '12116'), ('PE', '12118'), ('AU', '12120'), ('AE', '12122'), ('MT', '12132'), ('MF', '12133'), ('MP', '12134'), ('PM', '12135'), ('EM', '12138')], default='TM', max_length=5)),
                ('no_courses', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Falculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='subject',
            field=models.ManyToManyField(through='blog.Falculty', to='blog.Courses'),
        ),
        migrations.AddField(
            model_name='courses',
            name='dept',
            field=models.ManyToManyField(through='blog.Falculty', to='blog.Department'),
        ),
    ]
