# Generated by Django 3.0.7 on 2020-06-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subect_slug',
            new_name='subject_slug',
        ),
    ]
