# Generated by Django 3.0.7 on 2020-06-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='subject',
        ),
        migrations.AddField(
            model_name='post',
            name='courses',
            field=models.ManyToManyField(to='blog.Courses'),
        ),
        migrations.RemoveField(
            model_name='courses',
            name='dept',
        ),
        migrations.AddField(
            model_name='courses',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Department'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Falculty',
        ),
    ]
