# Generated by Django 3.0.7 on 2020-06-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_courses_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='number',
        ),
        migrations.AddField(
            model_name='courses',
            name='code',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
