# Generated by Django 3.0 on 2020-06-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineforum', '0004_chatforum_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatforum',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineforum.ChatForum'),
        ),
    ]
